### ISSUE TITLE
"Attach to tangle" returns "Invalid transaction hash"

### ISSUE THREAD

**Issue by alexdupre** [iotaledger/wallet#87] opened 2017-06-07 08:35 UTC
IOTA Light Wallet 2.2.6 connected to http://service.iotasupport.com:14265
When I try to attach my address to tangle I get "Request error: Invalid transaction hash"

**Comment by atypicalprogrammer** [comment] 2017-06-07 15:39
Duplicate of https://github.com/iotaledger/wallet/issues/88

**Closed by atypicalprogrammer** 2017-06-07 15:39 UTC
