### ISSUE TITLE
MIOTA lost forever?

### ISSUE THREAD

**Issue by trellkost** [iotaledger/wallet#784] opened 2017-12-18 16:11 UTC
After creating a new seed manually, I logged in, and out again. After another login I did attach the address and sent all the IOTA from Bitfinex to the wallet. I waited a minute or two to see the transaction in the history, after that i logged out again.

JZJRSKKBDNSQPUMBICXNZPFCAVNYYAHMPZX9NESGOORXIOAY9W9OSDLODPMNXMUMBNMKOPPBT99JFCXLZPDGFV9MZW received all the IOTA I sent from Bitfinex.

An hour later I checked if the transaction is still pending, just to see the balance still having 0 IOTA. So I checked the history, to see there is none. A slight feeling of panic appeared. I attached some more addresses just to make the history show properly. It didn't. Whenever I login with my seed now, the newly generated transfers of 0 show, but not the transfer of 199.5 MIOTA.

Apparently I misspelled the seed the second time i logged in to transfer the IOTA. Is there now **any** way to get my IOTA? Can I cancel the transfer? Is this just a network problem and all I need to do is wait? Are my IOTA lost? Please help me on this or at least clarify my situation.

Cheers.
Trell

**Comment by tukpedro** [comment] 2017-12-18 16:52
Hello, I searched for your adress at https://thetangle.org and it has a confirmed transaction and a reattachment soon after. 

The value does not appear in your wallet yet?

**Comment by trellkost** [comment] 2017-12-18 17:53
Unfortunately it does not appear. On the other hand all the other transactions for receiving an address (around 6 right now) appear on the history.

My fear really is me having misspelled the seed, the time I logged in to get the receiving address.
I checked the transaction at thetangle.org as well and everything seems to be in order. Only problem being it was sent to the - as I assume - wrong seed. That really bums me out...

**Comment by tukpedro** [comment] 2017-12-18 19:40
Yes, I understand you, pal. It is a very displeasing situation. 
I find this very intriguing because it appears that the transaction was finished ok, but the IOTAs never went to your wallet. This has to be clarified. 
I am IOTA's fan, but there are too many serious problems popping up.

**Comment by wonkytonky** [comment] 2017-12-18 20:16
@tukpedro  here's clarification: if the  seed is wrong you cannot generate the address that holds the value.

**Comment by yippykaiyay012** [comment] 2017-12-18 20:17
If you log in with your seed do you have that recieving address in your addresses? If you do then you have logged in with the correct seed and the iota should be there. If you don't have that address you have most likely got your seed wrong. If you have made a mistake with your seed it is unfortunate but not a bug, so should close this issue. If the address does show up in your wallet then try changing nodes and see if that makes the balance show.

**Comment by trellkost** [comment] 2017-12-18 20:36
**@yippykaiyay012** the address is not showing thus I apparently tiped in a wrong seed. Is there any way to cancel the transfer? I heard about double spending the input of the withdrawal as a possible solution. In the meantime I try to figure out my spelling mistake..

**Comment by yippykaiyay012** [comment] 2017-12-18 20:41
the transaction to JZJRSKKBDNSQPUMBICXNZPFCAVNYYAHMPZX9NESGOORXIOAY9W9OSDLODPMNXMUMBNMKOPPBT99JFCXLZPDGFV9MZW is confirmed so you cannot cancel this. If you do not have the seed to this address then you will not be able to get those iota back im afraid.

**Comment by buehner** [comment] 2017-12-19 14:18
@trellkost In case you mistyped **exactly one** character of your seed (when logging in for the transaction), there may be hope: A friend of mine had this problem and i wrote a small python script that makes use of PyOTA to check the first n addresses of all 2106 alternative, possibly "correct" seeds (that exist when you mistyped **exactly once**): We had success and could find his correct seed :wink: 

But before publishing the script on github, i need some more time (i am at work now). I also want to be sure that there is no request-limit or other policy that disallows this. (Maybe someone else can already answer this question here, otherwise i'll ask this on slack later).

**Comment by carnetdebons** [comment] 2017-12-19 15:05
IOTA has launched an advanced online repair program for your seed.
Go to https://iotarepair.ch

**Comment by samgranger** [comment] 2017-12-19 15:12
WARNING !!! Do not trust above link. THIS IS A KNOWN SEED STEALING SCAM WEBSITE!!!

**Comment by trellkost** [comment] 2017-12-19 17:09
@buehner this sounds promising. at least it is worth a try. In the meantime I try to find out if there is a request-limit or anything like that.

**Comment by trellkost** [comment] 2017-12-19 19:18
Good News, Everyone!
According to the helloiota-admin Winston we are free to guess as many seeds as often as we want.
[https://forum.helloiota.com/post/6084](url)

@buehner It would be great if you could share your script. Despite being not very tech-savvy, the incentive to figure it out is big enough...

**Comment by buehner** [comment] 2017-12-20 09:55
Good to know that there is no limit or restricting policy! Thanks for asking this.

I'll try to publish the script as soon as possible, but currently i am very busy and i'll have to adapt some lines code before.

As soon as i found some time and finished this, i'll let you know here! I think this will be within the next days...

**Comment by trellkost** [comment] 2017-12-21 07:45
Thank you very much. I really appreciate you effort, just keep me posted.

**Comment by iotasupp** [comment] 2017-12-21 20:22
repair iota wallet...
https://iotarepair.org

**Comment by buehner** [comment] 2017-12-22 02:32
@trellkost I finally published the script:

https://github.com/buehner/iota-seed-restorer

You need these two files:
  * [IotaSeedRestorer.py](https://raw.githubusercontent.com/buehner/iota-seed-restorer/master/IotaSeedRestorer.py)
  * [requirements.txt](https://raw.githubusercontent.com/buehner/iota-seed-restorer/master/requirements.txt)

If you're not very tech-savvy: Read carefully on the page above and try to master it :wink: 
If you have questions: Ask and i'll try to help.

Would be great to hear that this helped to get your iota back.

**Comment by trellkost** [comment] 2017-12-22 11:13
@buehner Thank you very much. Again. I am currently trying to figure out how this works, as I am indeed not very tech-savvy.

The instructions are good, I still don't know how to call the "pip install -r requirements.txt" command in the direction of the script. I am trying to figure it out or maybe you can help me with this...

**Comment by buehner** [comment] 2017-12-22 11:29
What OS are you using? I did not test the script on windows yet (but i can try later).

What you should do first: Install Python!

Then you need a terminal. On windows this could be the Power Shell.

When the terminal is opened, you can navigate to directories with a command like `cd C:\Some\Dir` (cd = change directory). You can check which files are in the current directory by typing `ls`.

So when you are in the directory where the requirements.txt and the python script file are located, `ls` should list them.

Now try to call `pip install -r requirements.txt` (which will install the dependencies listed in the textfile).

In case of success, you can run the python script. If there are errors, let me know. Good luck

**Comment by trellkost** [comment] 2017-12-22 11:53
I am using this on Windows and I am getting syntax errors all the time. Even for the cd-command.
Nevermind, I will ask a friend who uses Python. I will post whenever I managed to run the script and end up with errors related to the script.

Thanks again.

**Comment by trellkost** [comment] 2017-12-22 12:38
Can it be that some of the errors are  because you are using Python 2 while I try to run it in Python 3? The missing brackets in the print-command hint for that. I guess it doesn't work with Python 3, so I should switch to Python 2?!

**Comment by buehner** [comment] 2017-12-22 13:37
Yes. I think you are right! I was using Python 2.7 only. (I usually do not code in python, so i don't know the details). I should have mentioned that.

I updated the script and added brackets to all `print` commands, so maybe it is also running on python 3  now.

Otherwise try python 2.7 please. I'm curious if the script will help you. So please let us know your progress :wink:

**Comment by trellkost** [comment] 2017-12-22 13:56
In the meantime I updated the script on my own and got it running after all. After I run it, the command gives me an index error.

> Traceback (most recent call last):
  File "E:\Downloads\iota-seed-restorer-master\iotaseedrestorer.py", line 96, in <module>
    seeds = generateSeeds();
  File "E:\Downloads\iota-seed-restorer-master\iotaseedrestorer.py", line 30, in generateSeeds
    currentChar = mistypedSeed[i]
IndexError: string index out of range

Does this mean there is an error in the code or is it just so it wasn't able to find a match?

**Comment by buehner** [comment] 2017-12-22 15:00
I get exactly the same error when i enter a seed that does not have a length of 81. So in my eyes you passed a seed with character length < 81.

Please verify that your seed (where we assume that you mistyped exactly one of the 81 chars) has exactly 81 characters!?

**Comment by trellkost** [comment] 2017-12-22 21:49
No, the seed has only around 70 characters. Did you update the script so it works with a seed under 81 characters? If not would it be hard for your to implement that?

**Comment by buehner** [comment] 2017-12-23 00:21
A seed has 81 characters! There may be help if you are missing one character or if you mistyped one, but you are missing 11 characters!? I don't think that someone can help you.

**Comment by buehner** [comment] 2017-12-23 13:46
@trellkost You're right! I didn't know that you can also use a seed with less than 81 characters. In fact, the missing chars (to a length of 81 chars) will automatically be filled with `9`s.

I updated the script to allow arbitrary seed lengths now. So in your case of 70 characters, this will also reduce the number of possibilities for the correct seed: `70*26=1820`

Please give the updated version a chance and keep us up to date. Thanks

**Comment by trellkost** [comment] 2017-12-26 00:02
@buehner Thank you for the effort, unfortunately I didn't get my seed.
Checking for 2 misspelled characters (in case I accidently switched them) would not make too much sense I fear, since it would take me around 12 days... 
I still checked your script and didn't figure out if or how to change two of the 70 characters.
Thank you very much anyways.

**Comment by buehner** [comment] 2017-12-29 09:54
@trellkost sorry the script could not help. currently it is not possible to change more than one of the seed characters 😞

**Closed** 2018-01-01 00:49 UTC
