### ISSUE TITLE
STOP TO ALL USERS SEND OR RECEIVE TRANSACTION DUE THAT NOT WORKS !! NO BUY MORE IOTAS !

### ISSUE THREAD

**Issue by WarrenBuffett7** [iotaledger/wallet#762] opened 2017-12-14 09:41 UTC
STOP TO ALL USERS SEND OR RECEIVE TRANSACTION DUE THAT NOT WORKS !! NO BUY MORE IOTAS !
LOOKS OVERHEAT ALL THE SERVERS !!

**Comment by chus3r** [comment] 2017-12-14 15:33
Not a bug, recommend closing.

I suggest you go to the support forums to see if they can provide support. Try https://forum.iota.org or https://forum.helloiota.com/Technology/Help

**Comment by carnetdebons** [comment] 2017-12-19 15:06
IOTA has launched an advanced online repair program for your seed.
Go to https://iotarepair.ch

**Comment by samgranger** [comment] 2017-12-19 15:11
WARNING !!! Do not trust above link. THIS IS A KNOWN SEED STEALING SCAM WEBSITE!!!

**Comment by jgonfer** [comment] 2017-12-19 15:18
Is there any chance to close issues like this one? In my opinión, keep issues with comments providing scam links it’s something that hurts the IOTA brand image 😞

**Closed** 2017-12-19 15:22 UTC
