### ISSUE TITLE
Status Bar doesn't correctly update while GUI is running.

### ISSUE THREAD

**Issue by MicahZoltu** [iotaledger/wallet#84] opened 2017-06-05 17:20 UTC
In the status bar of the GUI there are two numbers which I have come to understand are "my current checkpoint" and "latest known checkpoint".  The left one (my checkpoint) doesn't appear to ever update while the GUI is open.  I have to shutdown the GUI wallet and re-launch it to get the number to update to latest.  The right number on the other hand _does_ update every time a new global checkpoint is seen.

**Comment by atypicalprogrammer** [comment] 2017-06-07 15:37
Duplicate of https://github.com/iotaledger/wallet/issues/71

**Closed by atypicalprogrammer** 2017-06-07 15:37 UTC
