### ISSUE TITLE
Unstable network

### ISSUE THREAD

**Issue by egek92** [iotaledger/wallet#742] opened 2017-12-12 14:24 UTC
We can't even do transactions to the wallet, how is this thing going to be the next bitcoin hahaha

**Comment by chus3r** [comment] 2017-12-12 21:03
Not a bug, recommend closing. 

I suggest you go to the support forums to see if they can provide support. Try https://forum.iota.org or https://forum.helloiota.com/Technology/Help

**Closed** 2018-10-26 07:45 UTC
