### ISSUE TITLE
DON'T BUY IOTA

### ISSUE THREAD

**Issue by andrewg12345** [iotaledger/wallet#664] opened 2017-12-07 13:44 UTC
WALLET IS A SCAM I lost ALL my iota using this wallet, its a total scam, you can put iota in, BUT and it a big but, you can not transfere it out.

IIts a total joke, you cant trust it

**Comment by andrewg12345** [comment] 2017-12-07 13:45
Just look how many people have lost money here. Total scam.

**Comment by Triztan** [comment] 2017-12-07 14:20
Can you explain about your issue?(transaction ids and so on)
Normal people uses the wallet everyday without any issue

**Comment by BullsEye72** [comment] 2017-12-07 14:28
Can confirm, I could withdraw from the wallet. It took several reattaches, but it worked.

**Comment by andrewg12345** [comment] 2017-12-07 14:28
I think you will find there have been plenty of posts, here and other forums, people have the same problem.

The upgradeed wallet has ZERO histoy, thus is unaccountable and untrust worthy.  Why would any sign up for this much grief.

I've never been able to transfer, i lost all that i tried to transfer, i just dont trust it. This could end up as the biggest scam in crypto. And people will soon realise it when they try to do a transfere from the wallet.

**Comment by Triztan** [comment] 2017-12-07 14:33
Have you checked about the "known issues" that you can solve just following some lines of text.
On IOTA Slack you will find a lot of resources that will help you to not get stuck like this

**Comment by andrewg12345** [comment] 2017-12-07 14:40
"known issues", its the ""unknown issues"", the ones they don't tel you about.

I've FFFing DAYS trying to get my iota back. Its just rediculous, most the the time it wont connect, 

Why have they released a wallet that nearly works for some? thats as bad as not working.

**Comment by Flieschi** [comment] 2017-12-07 15:31
at the moment bitcoin are faster then iota to confirm transfers. this is unbelievable and not acceptable for the FAST :( IOTA.

**Comment by Flieschi** [comment] 2017-12-07 15:37
@BullsEye72 
how offen you make rettaches to become transfer confirm?

**Comment by bberish** [comment] 2017-12-07 15:39
@andrewg12345 = FUD

Believe! I haven't been able to access my wallet for a few days now... but I still believe!

**Comment by andrewg12345** [comment] 2017-12-07 15:53
Well i'm not surprised i'm not the only one having issue. i've been struggling for MONTHS! its total crap!

**Comment by duduu** [comment] 2017-12-07 16:41
It is a total scam, I have 4 pending transactions since 4 days and I can not sell any of my miota because that. 
I can't see any type of support about it and there are many people with the same problem.

**Comment by BullsEye72** [comment] 2017-12-07 19:15
@Flieschi 
Well I had to try 6-7 times, I was always having a "Invalid Response" error...
But reconnecting to the node and trying to attach did finally happen after nearly 10 tries.
Not sure if it was the wallet or bitfinex node, with all this IOTA hype...
That being said, it was a scary time :)

**Comment by Sh0oky** [comment] 2017-12-07 19:25
yea, is not working...Don't use this Wallet!!!

**Comment by Alino** [comment] 2017-12-07 19:32
I am not wondering why the price went so much up when nobody can sell. Neither me. My transaction is stuck for 2 days still. Tried reattaching, rebroadcasting, switching nodes and repeating... Nothing works.
I am a conspiracy theorist and I suspect the team behind iota. They want to make iota popular fast so they manipulate the market this way. Once they deploy a fix, there will be a huge dump. Hehe

**Comment by Sergant212** [comment] 2017-12-07 22:18
This is very frightening. Such a real office and not what human technical support !!!. Complete nonsense!
4 days is not confirmed by the transaction, the new is not created !!
on the way at the expense of us and his PR went to such positions !!! beautifully made us loaches

**Comment by Sergant212** [comment] 2017-12-07 22:21
And how beautifully stelili about the most important transactions!

**Comment by Alino** [comment] 2017-12-07 22:28
Reasons to be concerned:

1. they have disabled their chat on slack for public https://github.com/iotaledger/wallet/issues/663
2. they are not responding much to us here.
3. their latest commit was **28 days ago**. 
4. the IOTA state is in catastrophic condition, both the tangle and the desktop wallet

**Comment by th0br0** [comment] 2017-12-07 22:37
1. no. https://join.slack.com/t/iotatangle/shared_invite/enQtMjgyODM0Njg0ODY0LTJmNmFhMjBkNzcxZWE2ZmIzODYyZGI3M2ZiYTRlY2M3MDc1NTJlM2I4YTFjZDQ3MjFjZjMzNGQwODEyYTZmNDE (just slack.iota.org is a tad broken because the link requires a reset every 1k users - thanks to our massive number of Slack users)
2. because this is not a customer support forum. this is an issue board for the wallet.
4. you shouldn't make claims without proofs.

Anyway, closing because this doesn't belong on a *bug* issue board.

**Closed by th0br0** 2017-12-07 22:37 UTC

**Comment by Sergant212** [comment] 2017-12-07 22:43
![screenshot_20171208004018](https://user-images.githubusercontent.com/34234967/33742393-ce83e890-dbb0-11e7-864a-9b078643553b.png)

**Comment by Sergant212** [comment] 2017-12-07 22:45
And there are two more that weigh! It's all okay with you !?

**Comment by Alino** [comment] 2017-12-07 22:48
3. Proof is here on github, latest commit was to the master branch and it was 28 days ago. If you have made commits on your dev machines, you should push for us to see.

**Comment by Alino** [comment] 2017-12-07 22:55
Also I think you shouldn't close this issue until concern number 4 is resolved. People should know that everything is fucked up and probably there will be a huge dump when people will be able to sell.
This is not just some fun project, people are putting a lot of money in this.

**Comment by Sergant212** [comment] 2017-12-07 23:05
All this resembles Russian roulette!
