### ISSUE TITLE
Balance is constantly 0

### ISSUE THREAD

**Issue by alex6058** [iotaledger/wallet#852] opened 2017-12-23 03:16 UTC
Hello,

I had install first time the IOTA Light Wallet and sent ~35Mi from Binance. After about 12 hours balance remains 0.

1. Status of transaction in thetangle.org is "confirmed": https://thetangle.org/transaction/CDRFFHUTPPQJA9KHKGKXTQKXMOHJXIYLBCSNQLWI9CYDINRPFAPLHOFIJHRSNY9XOZRDGCGHUKK9A9999

2. The history in the Wallet Application sometime is empty, sometime shows my transaction in the "pending" status. This condition changing all the time back and forth.

![screen shot iota](https://user-images.githubusercontent.com/34783950/34316478-78ad2660-e764-11e7-8dc1-df7ba22f4c4b.jpg)

3. Balance in the Wallet Application constantly remains zero 

4. Had been checked with versions 2.5.5 and 2.5.6 in the Linux and Mac OS        

5. Not sure it's important, but I never succeeded to "Attach the Tangle", always getting the error "invalid response". 
![screen shot 2017-12-22 at 10 10 32 pm copy](https://user-images.githubusercontent.com/34783950/34316522-864bca00-e765-11e7-8858-804051cf3822.jpg)

The server I use is bitfinex:
![screen shot 2017-12-22 at 10 12 09 pm](https://user-images.githubusercontent.com/34783950/34316520-7f329302-e765-11e7-8eea-8475c377a1eb.jpg)

**Comment by loopster40** [comment] 2017-12-23 04:13
Just try another node. I have had that situation before.

**Comment by ali59sh** [comment] 2017-12-23 12:01
i have the same problem abut 5 days.......

**Comment by mario589736** [comment] 2017-12-23 12:40
@alex6058 @ali59sh , same issue here: [843](https://github.com/iotaledger/wallet/issues/843). I described there what i think, what the problem is. I am on it, waiting for an answer from the IRI team at the moment - [IRI 433](https://github.com/iotaledger/iri/issues/433). If you post your hashes, i will index them also, if i find the solution.

**Comment by alex6058** [comment] 2017-12-23 14:44
@loopster40 your advice works! I just changed it from bitfinex to iotamexico.com it it magically refreshed: transaction status completed, balance is correct. I'm in USA so probably Mexico works better for me :D Nevertheless I need to do couple more transactions to make sure the system works fine. Thank you!

**Comment by alex6058** [comment] 2017-12-23 14:45
@mario589736 I just confirmed it seem to be a connection problem in my case

**Comment by mario589736** [comment] 2017-12-23 14:55
@alex6058 ok, thanks for the update. So this issue is closed?

**Comment by loopster40** [comment] 2017-12-23 15:06
Well, if it solves your issue then yeah. Whenever I have this issue. I just try different nodes and try to stay with that one node, unless it starts having connection issues. So if you see your balance then if you can close the ticket close it. Or state that it has been solved.


________________________________

**Comment by loopster40** [comment] 2017-12-23 15:09
Glad to hear it is working. When I first used the wallet I use to use the Mexico node, but for some reason, it does not work for me anymore. Mine connects now to another node. It's just the transaction will not update. So hopefully on one of the future updates it will correct itself.

________________________________

**Comment by loopster40** [comment] 2017-12-23 16:03
I started using this node and it seems to work fine http://5.9.118.112:14265

**Comment by alex6058** [comment] 2017-12-23 16:48
@mario589736 yes, I think this particular incident can be closed.

**Closed** 2018-01-01 00:14 UTC
