### ISSUE TITLE
Error while replay

### ISSUE THREAD

**Issue by pinpong** [iotaledger/wallet#73] opened 2017-06-02 23:12 UTC
I got this error on the first replay, second try works properly.

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
ui.history.js:105 undefined
ui.history.js:107 UI.replay: Error
ui.history.js:108 Error: Request Error: Invalid transaction hash
    at Object.requestError (iota.js:2621)
    at makeRequest.prepareResult (iota.js:3878)
    at exports.XMLHttpRequest.request.onreadystatechange (iota.js:3767)
    at exports.XMLHttpRequest.dispatchEvent (iota.js:17602)
    at setState (iota.js:17621)
    at exports.IncomingMessage.<anonymous> (iota.js:17458)
    at exports.IncomingMessage.EventEmitter.emit (iota.js:12084)
    at endReadableNT (iota.js:14445)
    at afterTickTwo (iota.js:12494)
    at Item.run (iota.js:12666)
    at drainQueue (iota.js:12636)
loading-btn.js:189 $.fn.loadingError: Request Error: Invalid transaction hash

**Comment by atypicalprogrammer** [comment] 2017-06-07 15:44
Duplicate of https://github.com/iotaledger/wallet/issues/88

**Closed by atypicalprogrammer** 2017-06-07 15:44 UTC
