### ISSUE TITLE
ERROR: PRIVATE KEY REUSE DETECTED Wallet 2.5.7

### ISSUE THREAD

**Issue by rnagler** [iotaledger/wallet#1067] opened 2018-01-29 10:32 UTC
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [ x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [ x] I confirm that this is an issue with the wallet, not IRI
* [ x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [ x] I confirm that this is not an issue related to stolen/lost funds
* [ x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ x] I confirm that this issue is present on the latest version of the wallet

### Description

After the Snapshot I try to send IOTAs to a new address. I get ERROR: PRIVATE KEY REUSE DETECTED but there are no pending transactions for this seed after the snapshot

### Steps to Reproduce

1. Start wallet, login, press send
2. Fill in Address, amount
3. Get Error message (several tries)

**Expected behavior:** send accepted

**Actual behavior:** ERROR
### Versions

Win10
Light Wallet 2.5.7
Host http://node.lukaseder.de:14265

**Comment by rnagler** [comment] 2018-01-29 10:39
Same ERROR with other seed, address and Host

**Comment by rnagler** [comment] 2018-01-29 10:44
see also #1053, but after snapshot and with new wallet

**Comment by wonkytonky** [comment] 2018-01-29 12:32
maybe the address you trying to send from was already used before snapshot

**Comment by resuschris** [comment] 2018-01-29 15:10
I got this problem. i solved it by making sure there was no unconfirmed transactions from my wallet. i systematically reattached pending Tx's and found i had an address generation that hadnt been confirmed that i reattached. this solved it

**Comment by rnagler** [comment] 2018-01-29 20:08
tried same send with iota-cli-app@1.0.8:
and got totally different error message:
iota (http://eugeneoldisoft.iotasupport.com:14265 ✓) 18ι : transfer xxx 18 
One moment while the transfer is made.  This can take a few minutes.
Error: Request Error: COMMAND attachToTangle is not available on this node

**Comment by rajivshah3** [comment] 2018-01-29 20:16
@rnagler you can use https://iotanode.us:443 as a host that allows `attachToTangle`. I'm closing this as it's not a bug

**Closed by rajivshah3** 2018-01-29 20:16 UTC

**Comment by rnagler** [comment] 2018-01-29 20:48
sorry, did also not work with light wallet 2.5.7 on this specific host, got same private key reuse error.
But it did work with iota-cli-app@1.0.8 on this host only:
@rajivshah3: Don't you think this is an wallet error when you get:
a) different error messages for same transaction on some nodes AND
b) different results for same transaction on one specific node?

See session example:
iota (http://eugeneoldisoft.iotasupport.com:14265 ✓) 18ι : node https://iotanode.us:443
Changing node to https://iotanode.us:443. This may take a few seconds for a remote node.  Did you turn on remote access?
iota (https://iotanode.us:443 ✓) 18ι : balance
One moment while we collect the data.
Your current balance is 18ι.
iota (https://iotanode.us:443 ✓) 18ι : transfer xxx 18 One moment while the transfer is made.  This can take a few minutes.
Transfer complete!
iota (https://iotanode.us:443 ✓) 18ι :

Here the hash from the cli tx:
EAEJDASQO9IGUVEVUKB9PBFXNTYTYTAAT9KWMVTUJAMKCDGGJHOTEGOLAVPZNNRVSFMXSTVOCTMO99999

**Comment by rajivshah3** [comment] 2018-01-29 20:51
Some nodes support attachToTangle, while others do not

**Comment by rnagler** [comment] 2018-01-29 21:01
"Some nodes support attachToTangle, while others do not" - fine with me, but this is an error anyway, because wallet does not send the correct error message - so the end user never will know what went wrong

**Comment by grantLF** [comment] 2018-02-20 16:19
Experiencing the following error using Light Wallet 2.5.7
ERROR: PRIVATE KEY REUSE DETECTED!
All I see are a series of 0 balance unconfirmed transactions - will not change status no matter how many attempts to reattach or promote - Appreciate any help. Thanks
