### ISSUE TITLE
In wallet 0 balans What happend

### ISSUE THREAD

**Issue by NIkola1967** [iotaledger/wallet#1005] opened 2018-01-14 13:14 UTC
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [ ] I confirm that this is an issue with the wallet, not IRI
* [ ] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [ ] I confirm that this is not an issue related to stolen/lost funds
* [ ] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [ ] I confirm that this issue is present on the latest version of the wallet

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

[OS Version]
[Wallet Version]

**Comment by NIkola1967** [comment] 2018-01-14 13:15
I wallet 0 balans what to do

**Comment by wonkytonky** [comment] 2018-01-14 13:22
change to a stable node

**Comment by Jim767676** [comment] 2018-01-14 21:34
Can confirm, I had zero balance and changed 'edit node config' under tools, changed to htt;://iota.bitfinex.com:80 and my balance re-appeared.

**Comment by asmilefixer** [comment] 2018-01-15 04:00
I cannot update on my mac to 2.5.6  I have rebroadcast on different nodes, but the deposit from 3 weeks ago still is pending.

Help please

**Comment by Jim767676** [comment] 2018-01-15 10:54
I have windows 10, not a mac, sorry!

**Comment by tryn2getedicated** [comment] 2018-01-17 06:59
I cannot get a balance on the wallet/ledger 2,5,6
I have pending bundles for 2 days  and there is balance shown for each transaction( after 24 hrs) but  balance at top shows 0   see below
I have reattatched-promoted-rebroadcast over and over
Should I change the curl or add more addresses or  change the node--Wallet seems to have the tokens,but why is balance still zero- I am sure I cannot transfer anything out and am afraid to try
Address does not show as needing to transition-only have wallet for 2 days now-no prev version
Funds wrere trans from binance and shows confirmed with 0 left there
Please advise-- using windosw7
Duplicate of 
Duplicate of ##1005


BALANCE

0
SEND

RECEIVE

HISTORY

12 Transfers 3 Addresses
17/01/2018 00:16
SWRDZGJD9NVKPBRHQXIQOIICPAUHPDDJV9YQJSVZMFZJOXDTAJOSLROWEBZ9VFFQVX9ZDFUALLBEUS9KCEKYHRRMLZ
Show bundle Pending
0
16/01/2018 23:11
ZVEOW9YCQUQRQSXX9MZREQSPYBXBZNYJ9BBWATGOHVMCCNGJLDB9F9HFKAETGJVKEZFFGHCIBMWYQOMQDDUIXUPYLY
AQAShow bundle Pending
549.5 Mi
16/01/2018 10:56
ZVEOW9YCQUQRQSXX9MZREQSPYBXBZNYJ9BBWATGOHVMCCNGJLDB9F9HFKAETGJVKEZFFGHCIBMWYQOMQDDUIXUPYLY
AQAShow bundle Pending
549.5 Mi
16/01/2018 08:19
HAERYXHQQDXGWOKJOFXTSDTOPMGJEIM9BRCRVVX9XSRCNUMU9IOOYGBD9VEEJABEEHIUYRMMFFCUBHBP9TAFKILHJA
Show bundle Pending
0
16/01/2018 08:10
ZVEOW9YCQUQRQSXX9MZREQSPYBXBZNYJ9BBWATGOHVMCCNGJLDB9F9HFKAETGJVKEZFFGHCIBMWYQOMQDDUIXUPYLY
QQAShow bundle Pending
9.5 Mi
16/01/2018 00:47
HAERYXHQQDXGWOKJOFXTSDTOPMGJEIM9BRCRVVX9XSRCNUMU9IOOYGBD9VEEJABEEHIUYRMMFFCUBHBP9TAFKILHJA
Show bundle Pending
0
16/01/2018 00:32
HAERYXHQQDXGWOKJOFXTSDTOPMGJEIM9BRCRVVX9XSRCNUMU9IOOYGBD9VEEJABEEHIUYRMMFFCUBHBP9TAFKILHJA
Show bundle Pending
0
16/01/2018 00:04
HAERYXHQQDXGWOKJOFXTSDTOPMGJEIM9BRCRVVX9XSRCNUMU9IOOYGBD9VEEJABEEHIUYRMMFFCUBHBP9TAFKILHJA
DWBShow bundle Pending
377.4+ Mi

**Comment by Jim767676** [comment] 2018-01-17 10:40
Keep trying the different addresses under 'edit node config'

**Comment by tryn2getedicated** [comment] 2018-01-18 00:24
ok-will try
thank you
will let U know

**Comment by tryn2getedicated** [comment] 2018-01-18 00:29
YOU ARE AWESOME JIM
ALL SHOWED UP WITH FIRST NODE CHANGE
IF YOU NEED SOME MED ADVICE <ASK ME -Ill give U ans-( but I am PED)

**Comment by Jim767676** [comment] 2018-01-18 00:39
Glad it worked for you, hope you bought the dip....   :)

**Closed** 2018-01-20 21:57 UTC
