### ISSUE TITLE
 Invalid transaction hash

### ISSUE THREAD

**Issue by Nyrsta** [iotaledger/wallet#50] opened 2017-05-23 20:56 UTC
with GUI lightwallet client during spamming or sending a value tx

05/23 16:52:21.779 [XNIO-1 task-31] ERROR com.iota.iri.service.API - API Exception:
java.lang.RuntimeException: Invalid transaction hash
        at com.iota.iri.TransactionValidator.runValidation(TransactionValidator.java:79) ~[iri-1.1.3.10.jar:na]
        at com.iota.iri.TransactionValidator.validate(TransactionValidator.java:85) ~[iri-1.1.3.10.jar:na]
        at com.iota.iri.service.API.broadcastTransactionStatement(API.java:621) [iri-1.1.3.10.jar:na]
        at com.iota.iri.service.API.process(API.java:218) [iri-1.1.3.10.jar:na]
        at com.iota.iri.service.API.processRequest(API.java:147) [iri-1.1.3.10.jar:na]
        at com.iota.iri.service.API.access$000(API.java:81) [iri-1.1.3.10.jar:na]
        at com.iota.iri.service.API$1.handleRequest(API.java:135) [iri-1.1.3.10.jar:na]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208) [iri-1.1.3.10.jar:na]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [iri-1.1.3.10.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

**Comment by atypicalprogrammer** [comment] 2017-06-07 15:39
Duplicate of https://github.com/iotaledger/wallet/issues/88

**Closed by atypicalprogrammer** 2017-06-07 15:39 UTC
