### ISSUE TITLE
SOFTWARE NOT COMING UP AFTER INSTALLATION

### ISSUE THREAD

**Issue by raymondokon** [iotaledger/wallet#135] opened 2017-06-24 12:52 UTC
Hi, I just downloaded and installed the iota wallet setup (Mainnet Release: v2.3.0), but it doesn't come up. I checked my task manager and I can see it's running in background processes but not in apps. I'm using windows 10 home, version 1703.
Please what do I do?

**Comment by atypicalprogrammer** [comment] 2017-06-25 07:02
use task manager to force quit it, then try again. If that doesn't work (force quit again), then open it via cmd.exe so that you can see the output of the application, and paste that output here.

**Comment by atypicalprogrammer** [comment] 2017-06-27 12:51
Duplicate of https://github.com/iotaledger/wallet/issues/125

**Closed by atypicalprogrammer** 2017-06-27 12:51 UTC

**Comment by Shree78** [comment] 2017-06-27 15:57
Hi, im facing the same issue with 2.3 not opening in windows 10, previous version of 2.2.6 was working well.
Can i use 2.2.6 instead of 2.3, for future works, would want to transfer fund from bitfinex to IOTA wallet for more security though, ASAP. Thanks
