### ISSUE TITLE
Certain wallets have become unaccessible. 

### ISSUE THREAD

**Issue by janimator0** [iotaledger/wallet#464] opened 2017-11-17 16:45 UTC
Today I woke up to find that I can no longer access my wallet. On the official IOTA desktop wallet, I receive "Connection Refused" whenever I try to connect with a specific seed. I have tried this on multiple Windows machines with the same result. I'm on the latest desktop wallet and have tried multiple nodes, all of which have not solved the issue. **Changing the last character of my seed will open a new wallet successfully** so I know there isn't a flaw in the format of my seed. At this point, I feel convinced that this is a bug in IOTA or there is an attack preventing people from accessing their funds.

**Comment by janimator0** [comment] 2017-11-17 20:57
I have now found 2 other users with similar issues.

**Comment by janimator0** [comment] 2017-11-17 22:36
Further investigation shows that this issue may be linked to mineiota.com . Which is a website that let's you mine monero in exchange for Iota. Users only need to provide their receiving address.

**Comment by th0br0** [comment] 2017-11-17 22:49
Connection refused usually indicates a bad node. 
I'm lacking information whether there is any real issue here. Changing the last letter of your seed should _not_ impact your wallet. 

Please provide me with more information via slack (@th0br0) or andreas@iota.org - I'll be closing the issue for the time being. 

I'm not following on the link to mineiota.com

**Closed by th0br0** 2017-11-17 22:49 UTC

**Comment by samuelgordon** [comment] 2017-11-22 21:15
I am having this same issue. Other seeds besides my own work just fine.

**Comment by janimator0** [comment] 2017-11-22 21:23
Yes. This is a known issue, for some reason, it is still marked as closed.  I was able to contact th0br0 to have my IOTA sent to a new wallet but had to forfeit my original seed (since it was acting weird). If you do contact him regarding this issue make sure that other seeds do work and you tried connecting multiple nodes. You can mention that your issue is similar to janimator0's where only your seed wont connect.

**Comment by th0br0** [comment] 2017-11-22 21:37
To update on this: we're working on a fix and will release a new wallet later this week to address this.
This is linked to there being more than 1000 TX on a single address of the seed, also see 
https://github.com/iotaledger/iri/issues/360 for more detail

**Comment by janimator0** [comment] 2017-11-22 21:41
Thanks for the update and looking forward to the fix!

**Comment by buragc** [comment] 2017-11-26 17:37
I have the same issue, should we just wait for the fix or contact @th0br0 at this point?

**Comment by janimator0** [comment] 2017-11-26 17:39
It sounds to me like waiting for a fix is the correct course of action as of right now.

**Comment by ThomasPepperz** [comment] 2017-11-26 19:04
A new wallet release is due out soon and should address wallet issues
involving address generation and login trouble. However, others are waiting
manual verification by Iota foundation for those whose seeds were exposed
due to address reuse or CURL_UNUSED statuses.

**Comment by mendogamers** [comment] 2017-12-04 23:54
i have the same problem ,i used mineiota.com. that is the proble, i have to wait a new version of the wallet?

**Comment by tobywilkins** [comment] 2017-12-05 17:47
I have the same issue... tried every node in the list... I can access any other seed apart from my own. I've never used 'mineiota' before

**Comment by onemoreitguy** [comment] 2017-12-05 17:58
same issue with me :(
Any update on the release date?

**Comment by anomaly15** [comment] 2017-12-05 22:27
Also checking for any update of release on new wallet?

**Comment by onemoreitguy** [comment] 2017-12-06 08:50
here's an update:
- I managed to create an IRI node with a 'workaround-no limit' with a copy from yesterday databases.
- I successfully managed to connect to my 'long-connection-refused-wallet' with all my balance

So the good news:
- If you have your wallet seed and an address (to check the balance the on the tangle), you didn't loose your wallet.
The 'not-so-good' news:
- You have to wait for a developers release of both wallet and IRI nodes
- Until then you cannot move your iotas
- I cannot get my node to sync with a full-node tangle (I try to request on slack, but no one is willing to...) so I don't want to provide access to anyone at this stage (they might just trying to send and receive, and then I cannot sync to the entire tangle)

Just have faith on the iota dev team.
I know a little more about the code and iota/tangle now, and I believe that they are fighting with a lot of issues and improvements to get a more stable version.

**Comment by tobywilkins** [comment] 2017-12-06 09:53
:man_facepalming: 

Is this issue affecting everyone? What is the actual issue its an issue with the full node software?

I've been trying to setup a 24/7 full node on a ubuntu VS - what do I need to do to mirror your configuration. Maybe we can be neighbours? 

Are the foundation team aware of this issue? surely its a relatively simple patch?

**Comment by onemoreitguy** [comment] 2017-12-06 11:37
The issue seems to affect specific wallets with a lot of transactions done.

The iota dev team is aware and from the code I would say that the fix needs to be done on the node and wallets. Cannot judge how simple or difficult is to solve, but it was not ready for such a large adoption of accumulated transactions at this point so they need time to provide a good code for users.

Look at the issue backlog, I would say that they are combining several patches for a single version.

**Comment by tobywilkins** [comment] 2017-12-06 11:57
Understood - they must be under a lot of pressure right now... thanks for the replies on here. 

If there is anything we can do to help to get more nodes online the I'm all ears

**Comment by onemoreitguy** [comment] 2017-12-06 13:48
I just need to me more close to the primary nodes. I'm always 20-30 Solid Milestone Index behind :(

**Comment by mar8887** [comment] 2017-12-06 17:52
That's good news... I'm kind of relieved that I'm not the only one with this issue and way more relieved to know that the devs could potentially access your wallet and get you your tokens back. 

In that case guys... Be super extra careful who and how that transaction is done. So far th0br0 seems the only legit person so far

**Comment by onemoreitguy** [comment] 2017-12-06 18:25
just to clarify:
- I'm not part of the dev team. Just a project enthusiast and follower as an IT guy 
- the dev team has no access to your wallets or seeds (I hope not !).
- The issue is the node/client don't currently handle wallets with large transactions
- I already managed to build a 'read-access-synced' (transactions not allowed) node, saw my wallets and tested successfully with other stressed users 
- The 'connection refused' is a standard error response to the client based on the real server response to the transaction limit exceed (you can see it using a wireshark http trace)

I'm here to help the dev team, community and not to trick anyone.
But I fully understand your judgment @mar8887. I trust you as much as you trust me ;)

**Comment by mar8887** [comment] 2017-12-06 18:38
Sorry, I didn't mean to sound as the devs could get your tokens as they wish (there's a formal way to do it through the wallet) 

Thank you for clarification. Is good to know you have friends in high places, ;)

**Comment by onemoreitguy** [comment] 2017-12-06 19:13
No friends at all on this community.... yet

**Comment by mendogamers** [comment] 2017-12-07 13:13
I solved the problem with this cluster of full nodes: https://nodes.iota.cafe:443

**Comment by anomaly15** [comment] 2017-12-08 06:49
@mendogamers I don't know what you mean as I tried this node just now too and it gives the exact same problem.

**Comment by onemoreitguy** [comment] 2017-12-08 09:20
@anomaly15 
If you know how to do HTTP/HTTPS packet capture you can look for the real cause.
If not, ping me and I can provide you temporary read access to my node.

**Comment by onemoreitguy** [comment] 2017-12-08 21:05
Just to summarize and let everyone to understand:
**ISSUE:** users are getting connection error when trying to sign-in
**CAUSE:** wallets with a significant amount of transactions are disconnected after awhile by the nodes. There is a limit defined that prevents large amount of data transfers (max:1000).
**WORKAROUND**: (a) install a full node (or find one). (b) Define on the ini file the following parameter MAX_REQUESTS_LIST=10000. (c) connect the wallet. It takes more than 10-60 minutes for the node and the wallet to process all the records
**SOLUTION**: wait for a node and wallet releases

Again: I'm not related to the dev team (I'm just a IOTA supporter and enthusiast) and I found this by searching and code reading
